// GENERATED by scripts/generate_developer_states.py -- do not edit by hand.
// The authority is core/coding_states.py. Run the script after changing it;
// tests/test_developer_states_sync.py fails while this file is stale.

export type StateKind = 'active' | 'success' | 'fault' | 'waiting' | 'idle'

export const STATE_KIND: Record<string, StateKind> = {
  approved: 'active',
  preparing: 'active',
  coding: 'active',
  validating: 'active',
  reviewing: 'active',
  pushed: 'active',
  merging: 'active',
  deploying: 'active',
  completed: 'success',
  locally_complete: 'success',
  failed: 'fault',
  rolled_back: 'fault',
  canceled: 'idle',
  paused: 'waiting',
  blocked: 'waiting',
  awaiting_merge_deploy_approval: 'waiting',
}

export type CodingStage = { id: string; title: string; capability: string | null }

export const STAGES: CodingStage[] = [
  { id: "prepare", title: "Create isolated worktree", capability: null },
  { id: "index", title: "Build scoped repository context", capability: null },
  { id: "code", title: "Run selected coding worker", capability: null },
  { id: "validate", title: "Run mandatory checks", capability: null },
  { id: "review", title: "Review scope, policy, and evidence", capability: null },
  { id: "commit", title: "Create logical checkpoint", capability: null },
  { id: "scan", title: "Perform final secret scan", capability: null },
  { id: "push", title: "Push feature branch", capability: "github" },
  { id: "pull_request", title: "Create draft pull request", capability: "github" },
  { id: "merge_deploy", title: "Owner merge and deploy gate", capability: "merge" },
  { id: "health", title: "Verify release health", capability: "deploy" },
]

export const STAGE_CAPABILITY: Record<string, string | null> =
  Object.fromEntries(STAGES.map(stage => [stage.id, stage.capability]))

function statesOfKind(...kinds: StateKind[]): Set<string> {
  return new Set(Object.entries(STATE_KIND).filter(([, k]) => kinds.includes(k)).map(([s]) => s))
}

/** Work is in flight and the runtime owns the session. */
export const ACTIVE_STATES = statesOfKind('active')
/** The run is over. Derived from STATE_KIND, so a new terminal state is never missed. */
export const TERMINAL_STATES = statesOfKind('success', 'fault', 'idle')
/** Finished without a fault -- 'completed' and 'locally_complete'. */
export const SUCCESS_STATES = statesOfKind('success')

export function stateKind(state: string): StateKind {
  return STATE_KIND[state] ?? 'idle'
}

/** The gates this policy actually allows a run to reach. */
export function permittedStages(capabilities: Record<string, boolean> | undefined): string[] {
  return STAGES.filter(s => !s.capability || Boolean(capabilities?.[s.capability])).map(s => s.id)
}
