// Morpheus visual identity.
//
// Morpheus is TOBI's private sibling: same shell mechanics, its own atmosphere. Rather than
// forking the design system, it overrides the SAME CSS variables Theme v2 defines
// (see src/context/themeTokens.ts). Every existing Tailwind token class -- bg-surface,
// text-muted, border-border -- therefore resolves to Morpheus values inside its shell and to
// TOBI values everywhere else, with no component changes and no second component library.
//
// The look is restraint, not decoration. Three rules hold it together:
//   1. ONE accent, heavily desaturated, used only for state that matters: the active page, the
//      primary action, focus. Everywhere else the neutrals and the type carry the design.
//   2. Depth comes from layered near-blacks and hairlines, never from glow or gradients.
//   3. One radius scale, one shadow scale, one spacing rhythm. No exceptions per component.

/** Channel triplets, matching Theme v2's "r g b" convention so `/10` opacity modifiers work. */
export const MORPHEUS_VARS: Record<string, string> = {
  // Neutrals: a near-black with a barely-perceptible cool cast. Never pure #000, which flattens
  // depth -- the whole design relies on being able to stack four dark planes and still see them.
  '--bg': '10 10 12',
  '--panel': '14 14 17',
  '--surface': '19 19 23',
  '--strip': '16 16 20',
  '--border': '35 35 42',
  // Measured, not guessed: at 122 this failed WCAG AA (4.38:1) against --surface, which is the
  // background it actually sits on inside every card. 134 clears 4.5:1 on both bg and surface.
  '--muted': '134 134 148',
  '--text': '201 201 209',
  '--heading': '244 244 247',

  // One accent: a muted iris. Desaturated on purpose -- a saturated violet is the single most
  // recognisable "generated by AI" tell, and restraint is what reads as expensive.
  '--accent': '143 134 217',
  '--purple': '143 134 217',
  '--theme-accent-2': '143 134 217',
  '--theme-glow': '143 134 217',
  '--selection': '143 134 217',

  // Status colours, muted to sit in the same world as the neutrals rather than shout over them.
  '--success': '106 187 141',
  '--warning': '206 160 90',
  '--danger': '214 96 104',

  '--overlay': '255 255 255',

  '--font-ui': '"Geist Variable", ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
  '--font-display': '"Geist Variable", ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
  '--font-numeric': 'tabular-nums',

  // One radius scale. Cards 12, controls 9, inputs 7 -- a consistent family, not per-component taste.
  '--radius-card': '12px',
  '--radius-button': '9px',
  '--radius-input': '7px',

  // Shadows are tinted toward the background hue and kept shallow. A dark UI gets its depth from
  // the surface stack; heavy drop shadows on near-black just look like smudges.
  '--shadow-card': '0 1px 2px rgb(0 0 0 / 0.4)',
  '--shadow-popover': '0 24px 60px -20px rgb(0 0 0 / 0.85), 0 0 0 1px rgb(35 35 42 / 0.9)',

  '--tracking-ui': '0em',
  '--bg-overlay-opacity': '0.03',
}

export const morpheusStyle = MORPHEUS_VARS as Record<string, string>

/**
 * Film grain, as a static repeating tile.
 *
 * Large flat near-blacks band visibly on 8-bit panels, and a trace of noise breaks the banding
 * while reading as film rather than as an effect. Used WITHOUT a blend mode and only on a fixed,
 * inert layer: `mix-blend-overlay` on a full-screen element forces the compositor to re-blend
 * the whole viewport every frame, which is the expensive part, not the texture itself.
 */
export const GRAIN_SVG =
  "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='160' height='160'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.8' numOctaves='2'/%3E%3C/filter%3E%3Crect width='160' height='160' filter='url(%23n)' opacity='0.5'/%3E%3C/svg%3E\")"

/**
 * Atmosphere behind the gate.
 *
 * TO REPLACE WITH A REAL PHOTOGRAPH: drop a dark aerial night-city image at
 * `dashboard/public/morpheus-gate.jpg` and it is picked up automatically. Until then the gate
 * renders a layered CSS atmosphere, which is deliberately built to stand on its own rather than
 * look like a missing image -- and unlike a remote URL it always works offline.
 */
export const MORPHEUS_GATE_IMAGE = '/morpheus-gate.jpg'

/** Arrival lines. Home picks one per visit so the greeting is never quite the same twice. */
export const GREETINGS: string[] = [
  'Welcome back, Thomas. Ready to cook?',
  'You are through. What are we opening tonight?',
  'The gate is sealed behind you, Thomas.',
  'No filters, no watchers. Just you and the work.',
  'Back in the dark, where the good work happens.',
  'Everything here is yours. Where do we start?',
]
