"""Generate the Mission Control mirror of the coding-workflow vocabulary.

`core/coding_states.py` is the authority. This script projects it into TypeScript so the
frontend classifies a workflow exactly the way the backend does, instead of maintaining a
hand-written copy that silently falls behind.

    python scripts/generate_developer_states.py            # write the file
    python scripts/generate_developer_states.py --check    # exit 1 if it is stale

`tests/test_developer_states_sync.py` runs the check, so a state added to Python without
regenerating fails the suite rather than reaching the UI as an unstyled unknown.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from core.coding_states import STAGES, STATE_KIND  # noqa: E402

TARGET = ROOT / "dashboard" / "src" / "developer.states.ts"


def render() -> str:
    kinds = "\n".join(f"  {state}: '{kind}'," for state, kind in STATE_KIND.items())
    stages = "\n".join(
        "  { id: %s, title: %s, capability: %s },"
        % (json.dumps(s["id"]), json.dumps(s["title"]), json.dumps(s["capability"]))
        for s in STAGES
    )
    return f"""// GENERATED by scripts/generate_developer_states.py -- do not edit by hand.
// The authority is core/coding_states.py. Run the script after changing it;
// tests/test_developer_states_sync.py fails while this file is stale.

export type StateKind = 'active' | 'success' | 'fault' | 'waiting' | 'idle'

export const STATE_KIND: Record<string, StateKind> = {{
{kinds}
}}

export type CodingStage = {{ id: string; title: string; capability: string | null }}

export const STAGES: CodingStage[] = [
{stages}
]

export const STAGE_CAPABILITY: Record<string, string | null> =
  Object.fromEntries(STAGES.map(stage => [stage.id, stage.capability]))

function statesOfKind(...kinds: StateKind[]): Set<string> {{
  return new Set(Object.entries(STATE_KIND).filter(([, k]) => kinds.includes(k)).map(([s]) => s))
}}

/** Work is in flight and the runtime owns the session. */
export const ACTIVE_STATES = statesOfKind('active')
/** The run is over. Derived from STATE_KIND, so a new terminal state is never missed. */
export const TERMINAL_STATES = statesOfKind('success', 'fault', 'idle')
/** Finished without a fault -- 'completed' and 'locally_complete'. */
export const SUCCESS_STATES = statesOfKind('success')

export function stateKind(state: string): StateKind {{
  return STATE_KIND[state] ?? 'idle'
}}

/** The gates this policy actually allows a run to reach. */
export function permittedStages(capabilities: Record<string, boolean> | undefined): string[] {{
  return STAGES.filter(s => !s.capability || Boolean(capabilities?.[s.capability])).map(s => s.id)
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if the file is stale")
    args = parser.parse_args()

    expected = render()
    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else None
    if args.check:
        if current == expected:
            print(f"{TARGET.relative_to(ROOT)} is current")
            return 0
        reason = "missing" if current is None else "stale"
        print(f"{TARGET.relative_to(ROOT)} is {reason}; run python scripts/generate_developer_states.py")
        return 1
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(expected, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
